---
- name: Add Golang ppa
  apt_repository:
    repo: 'ppa:gophers/archive'

- name: Install Golang 1.9
  apt:
    name: golang-1.9-go
    update_cache: yes

- name: Set GOROOT
  copy:
    src: goroot.sh
    dest: /etc/profile.d/gopath.sh
    owner: root
    group: root
    mode: 0644

- name: Set GOPATH
  lineinfile:
    path: /home/ibmcloud/.bashrc
    regexp: '^export GOPATH'
    line: 'export GOPATH=$HOME/go; export PATH=$PATH:$GOPATH/bin'
